### ISSUE TITLE
splicegrahm option j_incl

### ISSUE THREAD

**Issue by davidkundrat** [pkimes/spliceclust#1]
Hello there, 
I have recently discovered this amazing package for exon/junction visualization. Everything works fine, but I am having problems with one option in splicegrahm function, specificaly "j_incl". Whenever I try to use it (j_incl = TRUE), to display heatmaps for junctions, I recieve this error:
"Error in min(ranges(gr_e)) : invalid 'type' (S4) of argument"
At first I thought it might have been caused by wrong format of my GRanges and GRangesList data, but when I tried to follow manual with data supplied in package ("klk12_lusc_gr") I got the same error.
I tried to dig into those data formats a little more but couldn't find a solution to this.
Any help/input is much appreciated.
Thanks
David Kundrat

**Comment by pkimes** [comment]
@davidkundrat, thanks for reporting this.
I'll try to take a look at this tonight and get back to you. I haven't touched this code over the last couple of years, so my guess is that it has something to do with how the `GRanges` and `GRangesList` classes have changed over that time.

**Comment by pkimes** [comment]
@davidkundrat, I've updated the code, and it appears to now work with the example dataset included in the package. Let me know if you're still getting any errors. 

If everything is alright, let me know and I'll close this issue.

**Comment by davidkundrat** [comment]
@pkimes, first and foremost, thanks for really quick answer. 
I've reinstalled the package and it works perfectly with example dataset and even with my data, so thats great.
Thanks again for your work.
David
